import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { TOAST_DURATION } from "@/helpers/confirmableDelete";
import { ThemeProvider } from "@/components/ThemeProvider";
import CommandMenu from "@/components/CommandDialog";
import { DbProvider } from "@/contexts/dbContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DbProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <CommandMenu />
            <Toaster position="top-right" duration={TOAST_DURATION} />
          </ThemeProvider>{" "}
        </DbProvider>
      </body>
    </html>
  );
}
